### ISSUE TITLE
Error with latest RM package (with Ansible 2.9.2)

### ISSUE THREAD

**Issue by razikhussein** [IBM/osslm-ansible-resource-manager#89]
When we install the latest RM which come with Ansible 2.9.2, we started getting this error below.
My colleague informed me that ansible 2.9.2 works with Python 3.6, but the RM package come with Ansible 3.5, hence the error. Please advice. We tried to install 3.6 in the docker, but RM still refering to 3.5. Plese advice if there something we are missing

[2019-12-26 08:22:17,344] {lifecycle_controller_controller:66} ERROR - Transition request start failed: {'context': None,
[2019-12-26 08:24:41,985] {ans_handler:142} ERROR - task: 'Set facts' FAILED: Unexpected failure during module execution., [{'result': {'msg': 'Unexpected failure during module execution.', 'exception': 'Traceback (most recent call last):\n File "/usr/local/lib/python3.5/dist-packages/ansible/executor/task_executor.py", line 146, in run\n res = self._execute()\n File "/usr/local/lib/python3.5/dist-packages/ansible/executor/task_executor.py", line 601, in _execute\n self._connection = self._get_connection(variables=variables, templar=templar)\n File "/usr/local/lib/python3.5/dist-packages/ansible/executor/task_executor.py", line 892, in _get_connection\n ansible_playbook_pid=to_text(os.getppid())\n File "/usr/local/lib/python3.5/dist-packages/ansible/plugins/loader.py", line 573, in get\n obj = obj(*args, **kwargs)\n File "/usr/local/lib/python3.5/dist-packages/ansible/plugins/connection/network_cli.py", line 323, in __init__\n if self._play_context.verbosity > 3:\nTypeError: unorderable types: NoneType() > int()\n', 'stdout': '', '_ansible_no_log': False}, 'task': 'Set facts'}][Less]

**Comment by joschkappel** [comment]
Cant be recreated. This requires more information. 
ansible 2.9.0 as well as 2.9.2 work with python 3.5 (see https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#control-node-requirements ).
The "HelloWorld" example works without issues. 
Can you pls test with the "HelloWorld" example ?
From you log snippet is seems there is an issue with the network_cli module. Pls provide the failing playbook".

**Comment by razikhussein** [comment]
Apologies. My mistake in wording. Cloud engine device playbooks doesn't work on python 3.5, hence the error above.
We require ansible 2.9 with python 3.6 to resolve it, but unable to upgrade python to 3.6 in the rm docker

**Comment by joschkappel** [comment]
Can you pls try using attached Dockerfile and requirements.txt ?
[Archive.zip](https://github.com/IBM/osslm-ansible-resource-manager/files/4064882/Archive.zip)

```
docker-compose -f alm-ansible-rm-docker-compose.yml   build
```
then login to the container 
```
docker exec -ti ansible-rm bash
```
and verify with
```
python3 -V
ansible --version
```
pls let me know if this fixes your problem
